package noiseremoving;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 * Arin Bindra
 * 
 */

public class NoiseRemovingMain extends javax.swing.JFrame {

    public ImageIcon noiseImage = new ImageIcon();
    public ImageIcon cleanImage = new ImageIcon();
    public String noiseImageFile = new String();

    public NoiseRemovingMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel2.setText("");                                                         
    }
    
    //--------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        this.jButton1 = new javax.swing.JButton();
        this.jLabel2 = new javax.swing.JLabel();
        this.jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 650));

        this.jButton1.setText("Clean Image");
        this.jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        this.jLabel2.setText("");
        this.jLabel2.setMaximumSize(new java.awt.Dimension(400, 200));

        this.jButton3.setText("Select Image");
        this.jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(this.jButton3)
                        .addGap(20, 20, 20)
                        .addComponent(this.jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(100, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {this.jButton1, this.jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(this.jButton3)
                    .addComponent(this.jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {this.jButton1, this.jButton3});

        pack();
    }
    
    //--------------------------------------------------------------------------

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try 
        {
            if(this.noiseImageFile != null)
            {
                ImageProcess process2 = new ImageProcess(this.noiseImageFile);
                ImageIcon image2 = new ImageIcon(this.noiseImageFile);

                process2.cleanNoise();
                process2.save("noise_removed.jpg");

                ImageIcon imageIcon = new ImageIcon("noise_removed.jpg");

                ImageIcon largeImage2 = scaleImage(imageIcon.getImage());
                this.jLabel2.setIcon(largeImage2);
                this.cleanImage = largeImage2;
            }
        }
        catch (Exception e) 
        {
        }
    }
    
    //--------------------------------------------------------------------------
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) 
    {                                         
        try 
        { // Try get image 
            JFileChooser imageFileChooser = new JFileChooser(new File("."));
            int stateImageFileChooser = imageFileChooser.showOpenDialog(null);

            if (stateImageFileChooser == JFileChooser.APPROVE_OPTION) 
            {
                JFrame frame = new JFrame("");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                String file = imageFileChooser.getSelectedFile().getPath();
                this.noiseImageFile = file;

                ImageProcess process = new ImageProcess(file);
                ImageIcon imageIcon = new ImageIcon(file);
                
                ImageIcon scaledImage = scaleImage(imageIcon.getImage());
                this.jLabel2.setIcon(scaledImage);
                this.noiseImage = scaledImage;
            }
        } 
        catch (Exception E) 
        {
        }
    }
    
    //--------------------------------------------------------------------------
    
    private ImageIcon scaleImage(Image image)
    {
        ImageIcon scaledImage = new ImageIcon(image.getScaledInstance(this.jLabel2.getWidth(), this.jLabel2.getHeight(), Image.SCALE_SMOOTH));
        return scaledImage;
    }
    
    //--------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoiseRemovingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoiseRemovingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoiseRemovingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoiseRemovingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoiseRemovingMain().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
